include: package:very_good_analysis/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - build/**
    - lib/**.freezed.dart
    - lib/**.g.dart
  errors:
    sort_constructors_first: ignore
    public_member_api_docs: ignore
    use_setters_to_change_properties: ignore
    flutter_style_todos: ignore
    invalid_annotation_target: ignore
