---
dependencies:
  auto_exporter_annotation: any
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  riverpod_annotation: ^2.0.0
  shared_preferences: ^2.0.0
description: A helpful tool for riverpod developer.
dev_dependencies:
  auto_exporter: any
  build_runner: ^2.0.0
  build_test: ^2.0.0
  custom_lint: ^0.7.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.0.0
  riverpod_lint: ^2.0.0
  very_good_analysis: any
environment:
  flutter: '>=1.17.0'
  sdk: ^3.0.0
homepage: https://github.com/normidar/riverpod_helper
name: riverpod_helper
topics:
  - state
  - riverpod
  - preferences
  - state_management
  - helper
version: 0.0.3